SELECT ZAKAZNIK_ID , ZMLUVA_ID, PRODUKT_KOD, CISLO_KAROSERIE, ZMLUVA_DLH, DT_VYSTAVENIA 
  FROM DWHAPI.V_HEF_POHLADAVKY 
  WHERE ZAKAZNIK_ID = :anZakaznikId  AND PRODUKT_KOD<> :asProdukt  -- 87086 'SC'
  ORDER BY ZMLUVA_DLH DESC